### ISSUE TITLE
Not all PNGs get converted

### ISSUE THREAD

**Issue by pkozlowskifinder** [humanmade/tachyon#112] opened 2020-03-19 07:01 UTC
While trying to optimize this particular png with _?fit=100_ or _?w=100_ or _?webp=1_ Tachyon throws an error (probably from sharp) 
`Error: Input buffer contains unsupported image format` and the image that is returned is not changed. 

If there is something wrong with this particular png not Tachyon itself, could yout point what exactly? 

![fmp_SIMonlyNano](https://user-images.githubusercontent.com/61423091/77039567-82582300-69b6-11ea-86ad-0c4ebee88f13.png)

**Comment by roborourke** [comment] 2020-03-23 10:50
Do you have any info on how the image was made? What program it was saved from or anything like that?

**Comment by gregdawidko** [comment] 2020-03-25 09:09
Hey @roborourke , thanks for swift reply.
We did check but the person who uploaded no longer works with us and we don't know.
Do you know if we can check it somehow? Do you have a clue what could that image could have been?

**Comment by roborourke** [comment] 2020-07-22 10:00
@gregdawidko sorry for the long delay in following up here. I basically had no success reproducing the problem or understanding the root cause. It might possibly have been related to the fix in this PR #110  - some devices could create faulty image data. Normally sharp would just throw an error back but the update means it'll do its best. Hopefully 2.3.2 solves the problem anyway.

**Comment by roborourke** [comment] 2020-09-01 16:45
I think #110 solves this problem so closing out. We can reopen if that's not the whole problem

**Closed by roborourke** 2020-09-01 16:45 UTC
